# Generated by Django 6.0.6 on 2026-06-08 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadmintonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('court_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('shuttle_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('water_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('other_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('other_fee_note', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Đang mở'), ('settled', 'Đã quyết toán')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='groups.group')),
            ],
            options={
                'verbose_name': 'Buổi chơi',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_owed', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='sessions_app.badmintonsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Người tham gia',
                'unique_together': {('session', 'user')},
            },
        ),
    ]
