# Generated by Django 5.2.15 on 2026-06-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='bank_bin',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
