# Generated by Django 5.1.5 on 2026-06-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_bank_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='group_covers/'),
        ),
    ]
