# Generated by Django 5.1.5 on 2026-06-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='bank_qr',
            field=models.ImageField(blank=True, null=True, upload_to='bank_qr/'),
        ),
    ]
