# Generated by Django 5.1.5 on 2026-06-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_bank_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('badminton', '🏸 Chia tiền cầu lông'), ('meal', '🍜 Chia tiền cơm / ăn uống')], default='badminton', max_length=20),
        ),
    ]
