# Generated by Django 5.1.5 on 2026-06-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='is_participating',
            field=models.BooleanField(default=True),
        ),
    ]
