# Generated by Django 6.0.6 on 2026-06-08 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('debt_reminder', 'Nhắc nợ'), ('payment_request', 'Yêu cầu thanh toán'), ('payment_confirmed', 'Xác nhận thanh toán'), ('session_created', 'Buổi chơi mới')], max_length=30)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông báo email',
                'ordering': ['-created_at'],
            },
        ),
    ]
